services:
  - type: web
    name: daily-reflection-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: SECRET_KEY
        generateValue: true
